config_version: config_dlMU_dnn_61
optim: sgd
loss_fn: bcelogits
fast: distr_learner_mu
slow: dnn
random_seed: 999
num_blocks: 350
num_runs: 10
fast_config:
  attn_weighting: 0.05
  k: 0.01
  lesion: 0
  noise: 0
  optim: sgd
  loss_fn: bcelogits
  model_type: clustering
  max_nunits: 500
  n_dims: 2
  unit_recruit_type: feedback
  Phi: 1
  from_logits: true
  lr_attn: 0.002
  lr_nn: 0.001
  lr_units: 0.002
  momentum: 0
  random_seed: 999
slow_config:
  act_func: relu
  lr_dnn: 3
  n_units: 25
  mom: 0.0
  dropout: 0
  networks_depth: 3
  input_size: 2
  output_size: 2
  bias: true
  n_classes: 2
  optim: sgd
  loss_fn: bcelogits
