# --- clustering model config ---
max_num_clusters: 8
in_features: 3
out_features: 3
Phi: 10
asso_lr_multiplier: 1.0
high_attn_constraint: sumtoone
high_attn_lr_multiplier: 1.0
high_attn_regularizer: entropy
high_attn_reg_strength: 0.0
beta: 3.0
center_lr_multiplier: 1.0
config_version: config3
from_logits: true
lr_clustering: 0.1
num_blocks: 32
num_clusters: 8
num_runs: 50
q: 1
r: 2
random_seed: 999
specificity: 0.25
temp_competition: equivalent
temp_softwta: 0.012
thr: -0.4

# --- dnn model config --- 
act_func: relu
lr_dnn: 0.75
n_units: 25   # hidden layer size
mom: 0.
dropout: 0
networks_depth: 3
# n_sims: 50
# n_epochs: 350
input_size: 3
output_size: 2
# random_seed: 999
bias: True
n_classes: 2
