Phi: 10
act_func: relu
asso_lr_multiplier: 1.0
beta: 3.0
bias: true
center_lr_multiplier: 1.0
config_version: config18
dropout: 0
fast: clustering
from_logits: true
high_attn_constraint: sumtoone
high_attn_lr_multiplier: 1.0
high_attn_reg_strength: 0.0
high_attn_regularizer: entropy
in_features: 3
input_size: 3
loss_fn: bcelogits
lr_clustering: 0.1
lr_dnn: 5
max_num_clusters: 8
mom: 0.0
n_classes: 2
n_units: 25
networks_depth: 3
num_blocks: 350
num_clusters: 8
num_runs: 50
optim: sgd
out_features: 3
output_size: 2
q: 1
r: 2
random_seed: 999
slow: dnn
specificity: 0.25
temp_competition: equivalent
temp_softwta: 0.012
thr: -0.4
