config_version: config1
num_blocks: 10
num_runs: 10
optim: sgd
loss_fn: bcelogits
model_type: clustering
max_nunits: 50
n_dims: 2
unit_recruit_type: 'feedback'
Phi: 1
from_logits: true
lr_attn: 0.002
lr_nn: 0.025
lr_units: 0.002 # rob original = 0.005
momentum: 0
random_seed: 999